import Navbar from "@/components/navbar/page";
import "./globals.css";
import { Inter } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ESG MASTER | 중소기업 ESG 컨설팅",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
